### ISSUE TITLE
reading in spectra with astropy v1.0 vs astropy dev

### ISSUE THREAD

**Issue by crawfordsm** [astropy/specutils#119]
The following bit of code works using astropy dev but fails when using astropy v1.0.3 (the current pip installed version of astropy).  specutils was installed via pip in both test cases and is v0.10.

Here is the code:

```
 import specutils
 from astropy import units as u
 thar_spec = specutils.io.read_fits.read_fits_spectrum1d('thar.fits', dispersion_unit=u.angstrom)
 thar_spec.wavelength
```

And here is the error produced when run using astropy v1.0.3:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/crawford/temp/lib/python2.7/site-packages/specutils/spectrum1d.py", line 243, in __getattr__
return self.dispersion.to(self._wcs_attributes[name]['unit'], equivalencies=self.wcs.equivalencies)
File "/Users/crawford/temp/lib/python2.7/site-packages/specutils/spectrum1d.py", line 268, in dispersion
return self.wcs(self.indexer(pixel_indices))
File "/Users/crawford/temp/lib/python2.7/site-packages/specutils/wcs/specwcs.py", line 187, in __call__
self.param_sets))
File "/Users/crawford/temp/lib/python2.7/site-packages/specutils/wcs/specwcs.py", line 197, in evaluate
*coeffs) * unit
TypeError: unbound method evaluate() must be called with Spectrum1DPolynomialWCS instance as first argument (got ndarray instance instead)
```

I've copy of the file that is having the problem is available at:
http://pysalt.salt.ac.za/data/linelists/thar.fits

**Comment by wkerzendorf** [comment]
@crawfordsm yes I know this is an issue that is due to a change in modeling see #118. As I'm currently travelling, this is hard to fix right now.

**Comment by crawfordsm** [comment]
No worries and no rush on the fix as I have a work around.  I missed the other issue when I read through the list of issues so sorry for the duplication.   

Feel free to close this as I think this is mainly covered by #118

**Comment by wkerzendorf** [comment]
It should work now

**Comment by crawfordsm** [comment]
Just installed the development version, and it is still having the same problem.  Anything I might be missing?

**Comment by wkerzendorf** [comment]
@crawfordsm I did intend to merge, but it didn't do it on my phone. anyways - I merged now.

**Comment by wkerzendorf** [comment]
close if happy
